version: '2'

services:
    collector:
        image: orbsnetwork/message-bus
        ports:
            - 8080:3000
        env_file: ./.env.local.collector
        mem_limit: 256000000
        command: node ./collector/index.js
        restart: always

    gateway:
        image: orbsnetwork/message-bus
        ports:
            - 80:3000
        env_file: ./.env.local.gateway
        mem_limit: 256000000
        command: node ./gateway/index.js
        restart: always

    gamma:
        image: orbsnetwork/gamma:experimental
        ports:
            - 8090:8080
        restart: always

    mongo:
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        restart: always