version: '2'

services: 
    collector:
        image: orbsnetwork/message-bus
        ports:
            - 8080:3000
        env_file: ./.env.production.collector
        mem_limit: 256000000
        command: node ./collector/index.js

    gateway:
        image: orbsnetwork/message-bus
        ports:
            - 80:3000
        env_file: ./.env.production.gateway
        mem_limit: 256000000
        command: node ./gateway/index.js