version: '2'

services:
    collector:
        image: orbsnetwork/message-bus
        ports:
            - 8080:3000
        env_file: ./.env.local.collector
        mem_limit: 256000000
        command: node ./collector/index.js
        restart: always

    gateway:
        image: orbsnetwork/message-bus
        ports:
            - 80:3000
        env_file: ./.env.local.gateway
        mem_limit: 256000000
        command: node ./gateway/index.js
        restart: always

    gamma:
        image: orbsnetwork/gamma:experimental
        ports:
            - 8090:8080
        restart: always

    postgres:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: example
            POSTGRES_DB: message
        restart: always