version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@0.5.19
jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - node/install:
          node-version: '12.13.0'
      - docker/install-docker
      - run: node --version
      - run: npm --version
      - run: docker --version
      - run: env
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm install --no-save tap-xunit
      - run: mkdir -p _out/unit _out/e2e
      - node/with-cache:
          steps:
            - run: npm run build
      - run: docker-compose up -d
      - node/with-cache:
          steps:
            - run: npm run test # --  --timeout=10m --tap --no-color| npx tap-xunit > _out/e2e/test.xml
    #   - store_test_results:
    #       path: _out
    #   - store_artifacts:
    #       path: _out    

workflows:
  build-and-test:
    jobs:
      - build-and-test
